### ISSUE TITLE
Add discord-hs to Stackage

### ISSUE THREAD

**Issue by jano017** [jano017/Discord.hs#9]
The following steps need to be taken:
- [ ] Relax build constraints so latest libraries can be used
- [x] Replace wreq (isn't in lts-8.2 build) OR PR wreq to enable it to be added to the lts-8.2 build
- [ ] PR the stackage maintainers list to add me and d.hs to the build constraints file (Final step)

**Comment by TiltMeSenpai** [comment]
Done!
